language: python
python:
        - "3.4"
        - "3.3"
        - "3.5"
        - "3.6"
install:
        - pip install nose
        - pip install -e .
        # python 3.2 apparently doesn't have mock
        - pip install mock
script: python setup.py test
