language: python
python:
        - "3.4"
        - "3.3"
        - "3.5"
install:
        - pip install nose
        - pip install `python3 setup.py --requires`
        # python 3.2 apparently doesn't have mock
        - pip install mock
script: python setup.py test
